import type { StockMeta } from "./types";

export const NIKKEI225_STOCKS: StockMeta[] = [
  { code: "7203", symbol: "7203.T", nameJa: "トヨタ自動車",       sector: "輸送用機器" },
  { code: "9984", symbol: "9984.T", nameJa: "ソフトバンクG",      sector: "情報・通信" },
  { code: "6758", symbol: "6758.T", nameJa: "ソニーグループ",      sector: "電気機器" },
  { code: "6861", symbol: "6861.T", nameJa: "キーエンス",          sector: "電気機器" },
  { code: "8306", symbol: "8306.T", nameJa: "三菱UFJ FG",          sector: "銀行業" },
  { code: "6367", symbol: "6367.T", nameJa: "ダイキン工業",        sector: "機械" },
  { code: "4063", symbol: "4063.T", nameJa: "信越化学工業",        sector: "化学" },
  { code: "7974", symbol: "7974.T", nameJa: "任天堂",              sector: "その他製品" },
  { code: "4661", symbol: "4661.T", nameJa: "オリエンタルランド",  sector: "サービス業" },
  { code: "9433", symbol: "9433.T", nameJa: "KDDI",               sector: "情報・通信" },
  { code: "6954", symbol: "6954.T", nameJa: "ファナック",          sector: "電気機器" },
  { code: "8035", symbol: "8035.T", nameJa: "東京エレクトロン",    sector: "電気機器" },
  { code: "4519", symbol: "4519.T", nameJa: "中外製薬",            sector: "医薬品" },
  { code: "6902", symbol: "6902.T", nameJa: "デンソー",            sector: "輸送用機器" },
  { code: "9432", symbol: "9432.T", nameJa: "日本電信電話",        sector: "情報・通信" },
  { code: "2914", symbol: "2914.T", nameJa: "日本たばこ産業",      sector: "食料品" },
  { code: "8031", symbol: "8031.T", nameJa: "三井物産",            sector: "卸売業" },
  { code: "8058", symbol: "8058.T", nameJa: "三菱商事",            sector: "卸売業" },
  { code: "7267", symbol: "7267.T", nameJa: "本田技研工業",        sector: "輸送用機器" },
  { code: "6501", symbol: "6501.T", nameJa: "日立製作所",          sector: "電気機器" },
  { code: "4502", symbol: "4502.T", nameJa: "武田薬品工業",        sector: "医薬品" },
  { code: "9022", symbol: "9022.T", nameJa: "東海旅客鉄道",        sector: "陸運業" },
  { code: "8316", symbol: "8316.T", nameJa: "三井住友FG",          sector: "銀行業" },
  { code: "6752", symbol: "6752.T", nameJa: "パナソニック",        sector: "電気機器" },
  { code: "4503", symbol: "4503.T", nameJa: "アステラス製薬",      sector: "医薬品" },
  { code: "1928", symbol: "1928.T", nameJa: "積水ハウス",          sector: "建設業" },
  { code: "8801", symbol: "8801.T", nameJa: "三井不動産",          sector: "不動産業" },
  { code: "7751", symbol: "7751.T", nameJa: "キヤノン",            sector: "電気機器" },
  { code: "6098", symbol: "6098.T", nameJa: "リクルートHD",        sector: "サービス業" },
  { code: "2802", symbol: "2802.T", nameJa: "味の素",              sector: "食料品" },
  { code: "4523", symbol: "4523.T", nameJa: "エーザイ",            sector: "医薬品" },
  { code: "9020", symbol: "9020.T", nameJa: "東日本旅客鉄道",      sector: "陸運業" },
  { code: "3382", symbol: "3382.T", nameJa: "セブン&アイHD",       sector: "小売業" },
  { code: "4911", symbol: "4911.T", nameJa: "資生堂",              sector: "化学" },
  { code: "7741", symbol: "7741.T", nameJa: "HOYA",               sector: "精密機器" },
  { code: "6645", symbol: "6645.T", nameJa: "オムロン",            sector: "電気機器" },
  { code: "4543", symbol: "4543.T", nameJa: "テルモ",              sector: "精密機器" },
  { code: "8766", symbol: "8766.T", nameJa: "東京海上HD",          sector: "保険業" },
  { code: "5401", symbol: "5401.T", nameJa: "日本製鉄",            sector: "鉄鋼" },
  { code: "7733", symbol: "7733.T", nameJa: "オリンパス",          sector: "精密機器" },
  { code: "6503", symbol: "6503.T", nameJa: "三菱電機",            sector: "電気機器" },
  { code: "4901", symbol: "4901.T", nameJa: "富士フイルムHD",      sector: "化学" },
  { code: "8802", symbol: "8802.T", nameJa: "三菱地所",            sector: "不動産業" },
  { code: "9021", symbol: "9021.T", nameJa: "西日本旅客鉄道",      sector: "陸運業" },
  { code: "6702", symbol: "6702.T", nameJa: "富士通",              sector: "電気機器" },
  { code: "7270", symbol: "7270.T", nameJa: "SUBARU",             sector: "輸送用機器" },
  { code: "4151", symbol: "4151.T", nameJa: "協和キリン",          sector: "医薬品" },
  { code: "8309", symbol: "8309.T", nameJa: "三井住友TH",          sector: "銀行業" },
  { code: "2201", symbol: "2201.T", nameJa: "森永製菓",            sector: "食料品" },
  { code: "4578", symbol: "4578.T", nameJa: "大塚HD",              sector: "医薬品" },
];
