import type { StockMeta } from "./types";

export const NIKKEI225_STOCKS: StockMeta[] = [
  // 水産・農林業
  { code: "1332", symbol: "1332.T", nameJa: "日本水産",                   sector: "水産・農林業" },
  // 鉱業
  { code: "1605", symbol: "1605.T", nameJa: "INPEX",                      sector: "鉱業" },
  // 建設業
  { code: "1801", symbol: "1801.T", nameJa: "大成建設",                   sector: "建設業" },
  { code: "1802", symbol: "1802.T", nameJa: "大林組",                     sector: "建設業" },
  { code: "1803", symbol: "1803.T", nameJa: "清水建設",                   sector: "建設業" },
  { code: "1808", symbol: "1808.T", nameJa: "長谷工コーポレーション",     sector: "建設業" },
  { code: "1812", symbol: "1812.T", nameJa: "鹿島建設",                   sector: "建設業" },
  { code: "1860", symbol: "1860.T", nameJa: "戸田建設",                   sector: "建設業" },
  { code: "1878", symbol: "1878.T", nameJa: "大東建託",                   sector: "建設業" },
  { code: "1925", symbol: "1925.T", nameJa: "大和ハウス工業",             sector: "建設業" },
  { code: "1928", symbol: "1928.T", nameJa: "積水ハウス",                 sector: "建設業" },
  { code: "1963", symbol: "1963.T", nameJa: "日揮HD",                     sector: "建設業" },
  // 食料品
  { code: "2201", symbol: "2201.T", nameJa: "森永製菓",                   sector: "食料品" },
  { code: "2267", symbol: "2267.T", nameJa: "ヤクルト本社",               sector: "食料品" },
  { code: "2002", symbol: "2002.T", nameJa: "日清製粉グループ",           sector: "食料品" },
  { code: "2269", symbol: "2269.T", nameJa: "明治HD",                     sector: "食料品" },
  { code: "2282", symbol: "2282.T", nameJa: "日本ハム",                   sector: "食料品" },
  { code: "2501", symbol: "2501.T", nameJa: "サッポロHD",                 sector: "食料品" },
  { code: "2502", symbol: "2502.T", nameJa: "アサヒグループHD",           sector: "食料品" },
  { code: "2503", symbol: "2503.T", nameJa: "キリンHD",                   sector: "食料品" },
  { code: "2531", symbol: "2531.T", nameJa: "宝HD",                       sector: "食料品" },
  { code: "2768", symbol: "2768.T", nameJa: "双日",                       sector: "食料品" },
  { code: "2801", symbol: "2801.T", nameJa: "キッコーマン",               sector: "食料品" },
  { code: "2802", symbol: "2802.T", nameJa: "味の素",                     sector: "食料品" },
  { code: "2871", symbol: "2871.T", nameJa: "ニチレイ",                   sector: "食料品" },
  { code: "2875", symbol: "2875.T", nameJa: "東洋水産",                   sector: "食料品" },
  { code: "2897", symbol: "2897.T", nameJa: "日清食品HD",                 sector: "食料品" },
  { code: "2914", symbol: "2914.T", nameJa: "日本たばこ産業",             sector: "食料品" },
  // 繊維製品
  { code: "3105", symbol: "3105.T", nameJa: "日清紡HD",                   sector: "繊維製品" },
  { code: "3401", symbol: "3401.T", nameJa: "帝人",                       sector: "繊維製品" },
  { code: "3402", symbol: "3402.T", nameJa: "東レ",                       sector: "繊維製品" },
  // パルプ・紙
  { code: "3861", symbol: "3861.T", nameJa: "王子HD",                     sector: "パルプ・紙" },
  { code: "3863", symbol: "3863.T", nameJa: "日本製紙",                   sector: "パルプ・紙" },
  // 化学
  { code: "4004", symbol: "4004.T", nameJa: "レゾナック",                 sector: "化学" },
  { code: "4021", symbol: "4021.T", nameJa: "日産化学",                   sector: "化学" },
  { code: "4042", symbol: "4042.T", nameJa: "東ソー",                     sector: "化学" },
  { code: "4043", symbol: "4043.T", nameJa: "トクヤマ",                   sector: "化学" },
  { code: "4061", symbol: "4061.T", nameJa: "デンカ",                     sector: "化学" },
  { code: "4063", symbol: "4063.T", nameJa: "信越化学工業",               sector: "化学" },
  { code: "4114", symbol: "4114.T", nameJa: "日本触媒",                   sector: "化学" },
  { code: "4183", symbol: "4183.T", nameJa: "三井化学",                   sector: "化学" },
  { code: "4188", symbol: "4188.T", nameJa: "三菱ケミカルグループ",       sector: "化学" },
  { code: "4208", symbol: "4208.T", nameJa: "UBE",                        sector: "化学" },
  { code: "4452", symbol: "4452.T", nameJa: "花王",                       sector: "化学" },
  { code: "4612", symbol: "4612.T", nameJa: "日本ペイントHD",             sector: "化学" },
  { code: "4631", symbol: "4631.T", nameJa: "DIC",                        sector: "化学" },
  { code: "4901", symbol: "4901.T", nameJa: "富士フイルムHD",             sector: "化学" },
  { code: "4911", symbol: "4911.T", nameJa: "資生堂",                     sector: "化学" },
  // 医薬品
  { code: "4151", symbol: "4151.T", nameJa: "協和キリン",                 sector: "医薬品" },
  { code: "4502", symbol: "4502.T", nameJa: "武田薬品工業",               sector: "医薬品" },
  { code: "4503", symbol: "4503.T", nameJa: "アステラス製薬",             sector: "医薬品" },
  { code: "4506", symbol: "4506.T", nameJa: "住友ファーマ",               sector: "医薬品" },
  { code: "4507", symbol: "4507.T", nameJa: "塩野義製薬",                 sector: "医薬品" },
  { code: "4519", symbol: "4519.T", nameJa: "中外製薬",                   sector: "医薬品" },
  { code: "4523", symbol: "4523.T", nameJa: "エーザイ",                   sector: "医薬品" },
  { code: "4528", symbol: "4528.T", nameJa: "小野薬品工業",               sector: "医薬品" },
  { code: "4543", symbol: "4543.T", nameJa: "テルモ",                     sector: "医薬品" },
  { code: "4568", symbol: "4568.T", nameJa: "第一三共",                   sector: "医薬品" },
  { code: "4578", symbol: "4578.T", nameJa: "大塚HD",                     sector: "医薬品" },
  // 石油・石炭製品
  { code: "5019", symbol: "5019.T", nameJa: "出光興産",                   sector: "石油・石炭製品" },
  { code: "5020", symbol: "5020.T", nameJa: "ENEOSホールディングス",      sector: "石油・石炭製品" },
  { code: "5021", symbol: "5021.T", nameJa: "コスモエネルギーHD",         sector: "石油・石炭製品" },
  // ゴム製品
  { code: "5108", symbol: "5108.T", nameJa: "ブリヂストン",               sector: "ゴム製品" },
  { code: "5110", symbol: "5110.T", nameJa: "住友ゴム工業",               sector: "ゴム製品" },
  // ガラス・土石製品
  { code: "3436", symbol: "3436.T", nameJa: "SUMCO",                      sector: "ガラス・土石製品" },
  { code: "5201", symbol: "5201.T", nameJa: "AGC",                        sector: "ガラス・土石製品" },
  { code: "5214", symbol: "5214.T", nameJa: "日本電気硝子",               sector: "ガラス・土石製品" },
  { code: "5232", symbol: "5232.T", nameJa: "住友大阪セメント",           sector: "ガラス・土石製品" },
  { code: "5233", symbol: "5233.T", nameJa: "太平洋セメント",             sector: "ガラス・土石製品" },
  { code: "5301", symbol: "5301.T", nameJa: "東海カーボン",               sector: "ガラス・土石製品" },
  { code: "5332", symbol: "5332.T", nameJa: "TOTO",                       sector: "ガラス・土石製品" },
  { code: "5333", symbol: "5333.T", nameJa: "日本ガイシ",                 sector: "ガラス・土石製品" },
  { code: "5334", symbol: "5334.T", nameJa: "日本特殊陶業",               sector: "ガラス・土石製品" },
  // 鉄鋼
  { code: "5401", symbol: "5401.T", nameJa: "日本製鉄",                   sector: "鉄鋼" },
  { code: "5406", symbol: "5406.T", nameJa: "神戸製鋼所",                 sector: "鉄鋼" },
  { code: "5411", symbol: "5411.T", nameJa: "JFEホールディングス",        sector: "鉄鋼" },
  // 非鉄金属
  { code: "5706", symbol: "5706.T", nameJa: "三井金属",                   sector: "非鉄金属" },
  { code: "5711", symbol: "5711.T", nameJa: "三菱マテリアル",             sector: "非鉄金属" },
  { code: "5713", symbol: "5713.T", nameJa: "住友金属鉱山",               sector: "非鉄金属" },
  { code: "5714", symbol: "5714.T", nameJa: "DOWA HD",                    sector: "非鉄金属" },
  { code: "5741", symbol: "5741.T", nameJa: "UACJ",                       sector: "非鉄金属" },
  { code: "5801", symbol: "5801.T", nameJa: "古河電気工業",               sector: "非鉄金属" },
  { code: "5802", symbol: "5802.T", nameJa: "住友電気工業",               sector: "非鉄金属" },
  { code: "5803", symbol: "5803.T", nameJa: "フジクラ",                   sector: "非鉄金属" },
  // 金属製品
  { code: "5901", symbol: "5901.T", nameJa: "東洋製罐グループHD",         sector: "金属製品" },
  // 機械
  { code: "5631", symbol: "5631.T", nameJa: "日本製鋼所",                 sector: "機械" },
  { code: "6103", symbol: "6103.T", nameJa: "オークマ",                   sector: "機械" },
  { code: "6113", symbol: "6113.T", nameJa: "アマダ",                     sector: "機械" },
  { code: "6141", symbol: "6141.T", nameJa: "DMG森精機",                  sector: "機械" },
  { code: "6273", symbol: "6273.T", nameJa: "SMC",                        sector: "機械" },
  { code: "6301", symbol: "6301.T", nameJa: "コマツ",                     sector: "機械" },
  { code: "6302", symbol: "6302.T", nameJa: "住友重機械工業",             sector: "機械" },
  { code: "6305", symbol: "6305.T", nameJa: "日立建機",                   sector: "機械" },
  { code: "6326", symbol: "6326.T", nameJa: "クボタ",                     sector: "機械" },
  { code: "6361", symbol: "6361.T", nameJa: "荏原製作所",                 sector: "機械" },
  { code: "6367", symbol: "6367.T", nameJa: "ダイキン工業",               sector: "機械" },
  { code: "6383", symbol: "6383.T", nameJa: "ダイフク",                   sector: "機械" },
  { code: "6472", symbol: "6472.T", nameJa: "NTN",                        sector: "機械" },
  { code: "6471", symbol: "6471.T", nameJa: "日本精工",                   sector: "機械" },
  { code: "6473", symbol: "6473.T", nameJa: "JTEKT",                      sector: "機械" },
  { code: "6481", symbol: "6481.T", nameJa: "THK",                        sector: "機械" },
  { code: "6586", symbol: "6586.T", nameJa: "マキタ",                     sector: "機械" },
  // 電気機器
  { code: "6501", symbol: "6501.T", nameJa: "日立製作所",                 sector: "電気機器" },
  { code: "6503", symbol: "6503.T", nameJa: "三菱電機",                   sector: "電気機器" },
  { code: "6504", symbol: "6504.T", nameJa: "富士電機",                   sector: "電気機器" },
  { code: "6506", symbol: "6506.T", nameJa: "安川電機",                   sector: "電気機器" },
  { code: "6594", symbol: "6594.T", nameJa: "ニデック",                   sector: "電気機器" },
  { code: "6645", symbol: "6645.T", nameJa: "オムロン",                   sector: "電気機器" },
  { code: "6674", symbol: "6674.T", nameJa: "GSユアサ",                   sector: "電気機器" },
  { code: "6701", symbol: "6701.T", nameJa: "NEC",                        sector: "電気機器" },
  { code: "6702", symbol: "6702.T", nameJa: "富士通",                     sector: "電気機器" },
  { code: "6723", symbol: "6723.T", nameJa: "ルネサスエレクトロニクス",   sector: "電気機器" },
  { code: "6724", symbol: "6724.T", nameJa: "セイコーエプソン",           sector: "電気機器" },
  { code: "6752", symbol: "6752.T", nameJa: "パナソニックHD",             sector: "電気機器" },
  { code: "6754", symbol: "6754.T", nameJa: "アンリツ",                   sector: "電気機器" },
  { code: "6758", symbol: "6758.T", nameJa: "ソニーグループ",             sector: "電気機器" },
  { code: "6762", symbol: "6762.T", nameJa: "TDK",                        sector: "電気機器" },
  { code: "6770", symbol: "6770.T", nameJa: "アルプスアルパイン",         sector: "電気機器" },
  { code: "6841", symbol: "6841.T", nameJa: "横河電機",                   sector: "電気機器" },
  { code: "6857", symbol: "6857.T", nameJa: "アドバンテスト",             sector: "電気機器" },
  { code: "6861", symbol: "6861.T", nameJa: "キーエンス",                 sector: "電気機器" },
  { code: "6920", symbol: "6920.T", nameJa: "レーザーテック",             sector: "電気機器" },
  { code: "6952", symbol: "6952.T", nameJa: "カシオ計算機",               sector: "電気機器" },
  { code: "6954", symbol: "6954.T", nameJa: "ファナック",                 sector: "電気機器" },
  { code: "6971", symbol: "6971.T", nameJa: "京セラ",                     sector: "電気機器" },
  { code: "6976", symbol: "6976.T", nameJa: "太陽誘電",                   sector: "電気機器" },
  { code: "6981", symbol: "6981.T", nameJa: "村田製作所",                 sector: "電気機器" },
  { code: "6988", symbol: "6988.T", nameJa: "日東電工",                   sector: "電気機器" },
  { code: "8035", symbol: "8035.T", nameJa: "東京エレクトロン",           sector: "電気機器" },
  // 輸送用機器
  { code: "6902", symbol: "6902.T", nameJa: "デンソー",                   sector: "輸送用機器" },
  { code: "7011", symbol: "7011.T", nameJa: "三菱重工業",                 sector: "輸送用機器" },
  { code: "7012", symbol: "7012.T", nameJa: "川崎重工業",                 sector: "輸送用機器" },
  { code: "7013", symbol: "7013.T", nameJa: "IHI",                        sector: "輸送用機器" },
  { code: "7201", symbol: "7201.T", nameJa: "日産自動車",                 sector: "輸送用機器" },
  { code: "7202", symbol: "7202.T", nameJa: "いすゞ自動車",               sector: "輸送用機器" },
  { code: "7203", symbol: "7203.T", nameJa: "トヨタ自動車",               sector: "輸送用機器" },
  { code: "7211", symbol: "7211.T", nameJa: "三菱自動車工業",             sector: "輸送用機器" },
  { code: "7261", symbol: "7261.T", nameJa: "マツダ",                     sector: "輸送用機器" },
  { code: "7267", symbol: "7267.T", nameJa: "本田技研工業",               sector: "輸送用機器" },
  { code: "7269", symbol: "7269.T", nameJa: "スズキ",                     sector: "輸送用機器" },
  { code: "7270", symbol: "7270.T", nameJa: "SUBARU",                     sector: "輸送用機器" },
  { code: "7272", symbol: "7272.T", nameJa: "ヤマハ発動機",               sector: "輸送用機器" },
  // 精密機器
  { code: "6869", symbol: "6869.T", nameJa: "シスメックス",               sector: "精密機器" },
  { code: "7731", symbol: "7731.T", nameJa: "ニコン",                     sector: "精密機器" },
  { code: "7733", symbol: "7733.T", nameJa: "オリンパス",                 sector: "精密機器" },
  { code: "7741", symbol: "7741.T", nameJa: "HOYA",                       sector: "精密機器" },
  { code: "7751", symbol: "7751.T", nameJa: "キヤノン",                   sector: "精密機器" },
  { code: "7762", symbol: "7762.T", nameJa: "シチズン時計",               sector: "精密機器" },
  // その他製品
  { code: "7832", symbol: "7832.T", nameJa: "バンダイナムコHD",           sector: "その他製品" },
  { code: "7911", symbol: "7911.T", nameJa: "TOPPANホールディングス",     sector: "その他製品" },
  { code: "7912", symbol: "7912.T", nameJa: "大日本印刷",                 sector: "その他製品" },
  { code: "7974", symbol: "7974.T", nameJa: "任天堂",                     sector: "その他製品" },
  // 卸売業
  { code: "8001", symbol: "8001.T", nameJa: "伊藤忠商事",                 sector: "卸売業" },
  { code: "8002", symbol: "8002.T", nameJa: "丸紅",                       sector: "卸売業" },
  { code: "8015", symbol: "8015.T", nameJa: "豊田通商",                   sector: "卸売業" },
  { code: "8031", symbol: "8031.T", nameJa: "三井物産",                   sector: "卸売業" },
  { code: "8053", symbol: "8053.T", nameJa: "住友商事",                   sector: "卸売業" },
  { code: "8058", symbol: "8058.T", nameJa: "三菱商事",                   sector: "卸売業" },
  // 小売業
  { code: "3086", symbol: "3086.T", nameJa: "J.フロントリテイリング",     sector: "小売業" },
  { code: "3092", symbol: "3092.T", nameJa: "ZOZO",                       sector: "小売業" },
  { code: "3382", symbol: "3382.T", nameJa: "セブン&アイHD",              sector: "小売業" },
  { code: "8233", symbol: "8233.T", nameJa: "高島屋",                     sector: "小売業" },
  { code: "8252", symbol: "8252.T", nameJa: "丸井グループ",               sector: "小売業" },
  { code: "8267", symbol: "8267.T", nameJa: "イオン",                     sector: "小売業" },
  { code: "9843", symbol: "9843.T", nameJa: "ニトリHD",                   sector: "小売業" },
  { code: "9983", symbol: "9983.T", nameJa: "ファーストリテイリング",     sector: "小売業" },
  // 銀行業
  { code: "8304", symbol: "8304.T", nameJa: "あおぞら銀行",               sector: "銀行業" },
  { code: "8306", symbol: "8306.T", nameJa: "三菱UFJ FG",                 sector: "銀行業" },
  { code: "8308", symbol: "8308.T", nameJa: "りそなHD",                   sector: "銀行業" },
  { code: "8309", symbol: "8309.T", nameJa: "三井住友TG",                 sector: "銀行業" },
  { code: "8316", symbol: "8316.T", nameJa: "三井住友FG",                 sector: "銀行業" },
  { code: "8354", symbol: "8354.T", nameJa: "ふくおかFG",                 sector: "銀行業" },
  { code: "8355", symbol: "8355.T", nameJa: "静岡銀行",                   sector: "銀行業" },
  { code: "8411", symbol: "8411.T", nameJa: "みずほFG",                   sector: "銀行業" },
  // 証券・商品先物取引業
  { code: "8601", symbol: "8601.T", nameJa: "大和証券グループ本社",       sector: "証券業" },
  { code: "8604", symbol: "8604.T", nameJa: "野村HD",                     sector: "証券業" },
  { code: "8628", symbol: "8628.T", nameJa: "松井証券",                   sector: "証券業" },
  // 保険業
  { code: "8630", symbol: "8630.T", nameJa: "SOMPOホールディングス",      sector: "保険業" },
  { code: "8725", symbol: "8725.T", nameJa: "MS&ADインシュアランスGHD",   sector: "保険業" },
  { code: "8750", symbol: "8750.T", nameJa: "第一生命HD",                 sector: "保険業" },
  { code: "8766", symbol: "8766.T", nameJa: "東京海上HD",                 sector: "保険業" },
  // その他金融業
  { code: "8591", symbol: "8591.T", nameJa: "オリックス",                 sector: "その他金融業" },
  // 不動産業
  { code: "3289", symbol: "3289.T", nameJa: "東急不動産HD",               sector: "不動産業" },
  { code: "8801", symbol: "8801.T", nameJa: "三井不動産",                 sector: "不動産業" },
  { code: "8802", symbol: "8802.T", nameJa: "三菱地所",                   sector: "不動産業" },
  { code: "8804", symbol: "8804.T", nameJa: "東京建物",                   sector: "不動産業" },
  { code: "8830", symbol: "8830.T", nameJa: "住友不動産",                 sector: "不動産業" },
  // 陸運業
  { code: "9001", symbol: "9001.T", nameJa: "東武鉄道",                   sector: "陸運業" },
  { code: "9005", symbol: "9005.T", nameJa: "東急",                       sector: "陸運業" },
  { code: "9007", symbol: "9007.T", nameJa: "小田急電鉄",                 sector: "陸運業" },
  { code: "9008", symbol: "9008.T", nameJa: "京王電鉄",                   sector: "陸運業" },
  { code: "9009", symbol: "9009.T", nameJa: "京成電鉄",                   sector: "陸運業" },
  { code: "9020", symbol: "9020.T", nameJa: "東日本旅客鉄道",             sector: "陸運業" },
  { code: "9021", symbol: "9021.T", nameJa: "西日本旅客鉄道",             sector: "陸運業" },
  { code: "9022", symbol: "9022.T", nameJa: "東海旅客鉄道",               sector: "陸運業" },
  { code: "9064", symbol: "9064.T", nameJa: "ヤマトHD",                   sector: "陸運業" },
  { code: "9143", symbol: "9143.T", nameJa: "SGホールディングス",         sector: "陸運業" },
  { code: "9147", symbol: "9147.T", nameJa: "NIPPON EXPRESS HD",          sector: "陸運業" },
  // 海運業
  { code: "9101", symbol: "9101.T", nameJa: "日本郵船",                   sector: "海運業" },
  { code: "9104", symbol: "9104.T", nameJa: "商船三井",                   sector: "海運業" },
  { code: "9107", symbol: "9107.T", nameJa: "川崎汽船",                   sector: "海運業" },
  // 空運業
  { code: "9201", symbol: "9201.T", nameJa: "日本航空",                   sector: "空運業" },
  { code: "9202", symbol: "9202.T", nameJa: "ANAホールディングス",        sector: "空運業" },
  // 倉庫・運輸関連業
  { code: "9301", symbol: "9301.T", nameJa: "三菱倉庫",                   sector: "倉庫・運輸関連業" },
  // 情報・通信
  { code: "4307", symbol: "4307.T", nameJa: "野村総合研究所",             sector: "情報・通信" },
  { code: "4689", symbol: "4689.T", nameJa: "LINEヤフー",                 sector: "情報・通信" },
  { code: "9432", symbol: "9432.T", nameJa: "日本電信電話",               sector: "情報・通信" },
  { code: "9433", symbol: "9433.T", nameJa: "KDDI",                       sector: "情報・通信" },
  { code: "9434", symbol: "9434.T", nameJa: "ソフトバンク",               sector: "情報・通信" },
  { code: "9613", symbol: "9613.T", nameJa: "NTTデータグループ",          sector: "情報・通信" },
  { code: "9984", symbol: "9984.T", nameJa: "ソフトバンクG",              sector: "情報・通信" },
  // 電気・ガス業
  { code: "9501", symbol: "9501.T", nameJa: "東京電力HD",                 sector: "電気・ガス業" },
  { code: "9502", symbol: "9502.T", nameJa: "中部電力",                   sector: "電気・ガス業" },
  { code: "9503", symbol: "9503.T", nameJa: "関西電力",                   sector: "電気・ガス業" },
  { code: "9504", symbol: "9504.T", nameJa: "中国電力",                   sector: "電気・ガス業" },
  { code: "9531", symbol: "9531.T", nameJa: "東京ガス",                   sector: "電気・ガス業" },
  { code: "9532", symbol: "9532.T", nameJa: "大阪ガス",                   sector: "電気・ガス業" },
  // サービス業
  { code: "2413", symbol: "2413.T", nameJa: "エムスリー",                 sector: "サービス業" },
  { code: "3099", symbol: "3099.T", nameJa: "H2Oリテイリング",            sector: "サービス業" },
  { code: "4324", symbol: "4324.T", nameJa: "電通グループ",               sector: "サービス業" },
  { code: "4661", symbol: "4661.T", nameJa: "オリエンタルランド",         sector: "サービス業" },
  { code: "6098", symbol: "6098.T", nameJa: "リクルートHD",               sector: "サービス業" },
  { code: "9602", symbol: "9602.T", nameJa: "東宝",                       sector: "サービス業" },
  { code: "9735", symbol: "9735.T", nameJa: "セコム",                     sector: "サービス業" },
  { code: "9766", symbol: "9766.T", nameJa: "コナミグループ",             sector: "サービス業" },
];
